version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    command: python manage.py runserver
    volumes:
      - .:/app
    ports:
      - "8000:8000"
